let projectCollection = {
  "projects": [
  {
    "Timestamp": "2021/11/23 10:07:37 PM EST",
    "Username": "yy2901@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Yuhao Yang",
    "Email": "yy2901@nyu.edu",
    "Net ID": "yy2901",
    "Link to your personal portfolio": "yuhao.io",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=12FGdypI92lcusu9Zpr2o-nYPKNmvD7qp",
    "Supplementary photos": "",
    "Instagram Handle": "",
    "Linked In": "https://www.linkedin.com/in/yuhao-yang-8b1541113/",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Content Management System",
    "Title of your project": "A Lightweight Content Management System",
    "Short Description of your work (1 sentence)": "A lightweight CMS for creatives to use as a backend for their portfolio websites.",
    "Long Description of your work (4-6 sentences)": "A lightweight CMS for creatives to use as a backend for their portfolio websites. A Visualized JSON editor + REST API for frontend web developers to easily custom fields and serve data for frontend projects.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1qSqsr-KnPVx3Bs1bBq6ZuTt1F15tJbr7",
    "Supporting Images": "",
    "Project Link": "https://github.com/yy2901/senior-project-cms-backend",
    "Project Hashtag #": "",
    "Project Themes & Keywords": ""
  },
  {
    "Timestamp": "2021/11/25 11:42:03 PM EST",
    "Username": "mar1177@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Adlan Arvyanda Ramly",
    "Email": "mar1177@nyu.edu",
    "Net ID": "mar1177",
    "Link to your personal portfolio": "http://adlanramly.com/",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1mr22igdG9GcEjqNCvAFdNzKbqDqaDWh9",
    "Supplementary photos": "",
    "Instagram Handle": "adlanar",
    "Linked In": "https://www.linkedin.com/in/adlanramly",
    "Twitter Handle": "adlanarv",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Final Year Grad (Thesis Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Game",
    "Title of your project": "Project Anomaly: Urban Supernatural Investigator",
    "Short Description of your work (1 sentence)": "Project Anomaly: Urban Supernatural Investigator is a 2.5D first-person adventure mystery game where you play as an investigator who solves cases by taking pictures of cryptids, urban legends, & mythological creatures as well as befriending them in an open-world environment",
    "Long Description of your work (4-6 sentences)": "Project Anomaly: Urban Supernatural Investigator is a 2.5D first-person adventure mystery game where you play as an investigator who solves cases by taking pictures of cryptids, urban legends, & mythological creatures as well as befriending them in an open-world environment.\n\nA discovery-focused light-action narrative game with an emphasis on taking pictures & reading character dialogues as well as research entries to solve cases. The game is structured in short 6 minutes of gameplay in every investigation shift where players accumulate incremental research progress throughout investigations.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1vep5jtjlJYCny7TP__qs1rgIfKXSiX1m",
    "Supporting Images": "",
    "Project Link": "https://darksciencelabs.itch.io/projectanomaly-pilot",
    "Project Hashtag #": "ProjectAnomaly",
    "Project Themes & Keywords": "game, games, indie, indie game, photography, mystery, adventure, fps, scifi, supernatural, paranormal, mythology, narrative"
  },
  {
    "Timestamp": "2021/11/26 9:04:43 PM EST",
    "Username": "amc1347@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Alison Chen",
    "Email": "amc1347@nyu.edu",
    "Net ID": "amc1347",
    "Link to your personal portfolio": "alisonmchen.site",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=18eFUJKnyteJl1sYx2W_pyVh3P-fACOjS",
    "Supplementary photos": "",
    "Instagram Handle": "alt0ids",
    "Linked In": "https://www.linkedin.com/in/chenalison4/?_l=en_US",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Wearable",
    "Title of your project": "Chained to a Prescription Pill Dependency",
    "Short Description of your work (1 sentence)": "This piece is a representation of the physical and mental reliance on prescription drugs in the form of a wearable.",
    "Long Description of your work (4-6 sentences)": "After being diagnosed with a mental health disorder in 2018, I started collecting all of my pill bottles. This made me realized the sheer amount of prescriptions that Americans with diagnosed illnesses are prescribed each year. After three years, I've collected over 150 bottles and wanted to make a piece of art that represents a prescription medication dependency. I wanted to show that these patients try to break free from their prescriptions but are still chained to their medication because of their diagnosis. My piece is made up of wire, broken pill bottles, and rings to symbolize chains.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1AJUOAovGjREqKh5soYVUJsqER8qmswEM",
    "Supporting Images": "",
    "Project Link": "https://www.alisonmchen.site/projects/senior-project",
    "Project Hashtag #": "",
    "Project Themes & Keywords": ""
  },
  {
    "Timestamp": "2021/11/26 10:55:45 PM EST",
    "Username": "elu206@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Erin Utter",
    "Email": "elu206@nyu.edu",
    "Net ID": "elu206",
    "Link to your personal portfolio": "https://erinutter.wixsite.com/portfolio",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1C5qnPAmd6ssoj_RfxZKr5EpLeHHs_v2H",
    "Supplementary photos": "",
    "Instagram Handle": "",
    "Linked In": "www.linkedin.com/in/erin-utter",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "UX Project",
    "Title of your project": "Writers' Block",
    "Short Description of your work (1 sentence)": "Writers' Block is a social media app for writers to find and create writing communities.",
    "Long Description of your work (4-6 sentences)": "As someone who writes occasionally, I know that writing can be an isolating experience.  Without support, it can sometimes be difficult to feel motivated.  I  wanted to create an app that helps writers find community and encouragement for their work.  I created this UX project and designed an app for writers to find and create writers groups.  The app is also designed to allow for writers to find articles for tips on writing as well as events in their area.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1-mhfC2vS7YxQ5fZ-smKkZ8verm5h1I5M",
    "Supporting Images": "",
    "Project Link": "https://www.figma.com/proto/m7IuoZYMN6tp459N1wjjsA/writers'-block?page-id=255%3A2&node-id=255%3A2382&viewport=241%2C48%2C0.09&scaling=scale-down&starting-point-node-id=255%3A2382",
    "Project Hashtag #": "writersblock",
    "Project Themes & Keywords": "ux design, communication, social media, writing"
  },
  {
    "Timestamp": "2021/11/27 10:56:03 AM EST",
    "Username": "mmw9774@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Matthew Winnicki",
    "Email": "mmw9774@nyu.edu",
    "Net ID": "N18454482",
    "Link to your personal portfolio": "https://www.matthewwinnicki.com/",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1Sl7QK6937i17Mo31WxWQR8ciWb283-tx",
    "Supplementary photos": "",
    "Instagram Handle": "@matmicwin",
    "Linked In": "https://www.linkedin.com/in/matthewwinnicki/",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Final Year Grad (Thesis Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Game",
    "Title of your project": "Left",
    "Short Description of your work (1 sentence)": "Left is a virtual walkthrough based on the concept of mind-uploading and immortality.",
    "Long Description of your work (4-6 sentences)": "I was inspired to create to create my project based off of the idea of Posthumanism. I wanted to show users what it may be like to live as immortal beings thanks to advanced technology. The user will navigate through a virtual world by walking around and interacting with various characters. All of these characters are mind-uploaded avatars who are either pro or anti mind-uploading.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1nFBUUpOCbL10H1lt1HtJXaj4mpDQDtw-",
    "Supporting Images": "https://drive.google.com/u/0/open?usp=forms_web&id=184rdD2ZveEqsDB7PH900-raaq_jsZk7r;https://drive.google.com/u/0/open?usp=forms_web&id=1bhRj8TqRWC3epzfgmkqQvmIxIl74N_w2;https://drive.google.com/u/0/open?usp=forms_web&id=1aVzo0Uqmy4TFz7S4zR0q0tB24WczB7xB;https://drive.google.com/u/0/open?usp=forms_web&id=18qX5MBq5a3RvaQCTleuVTlCjoYdGijSB",
    "Project Link": "https://www.matthewwinnicki.com/left",
    "Project Hashtag #": "#leftmw",
    "Project Themes & Keywords": "Posthumanism, Whole Brain Emulation, Immortality, Virtual Reality"
  },
  {
    "Timestamp": "2021/11/27 8:06:56 PM EST",
    "Username": "sr4577@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Shehara Ranasinghe",
    "Email": "shehararan@nyu.edu",
    "Net ID": "sr4577",
    "Link to your personal portfolio": "https://shehararan.com",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1Sd9PcoSHa92rifrmNyaz6FTlQv_mACog",
    "Supplementary photos": "https://drive.google.com/u/0/open?usp=forms_web&id=1cs9PTNLD00D9FIQTAVXHfD6MLvmBwoZD",
    "Instagram Handle": "shehararanas",
    "Linked In": "https://www.linkedin.com/in/shehararanasinghe/",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Final Year Grad (Thesis Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Instagram Page and AR Filters",
    "Title of your project": "Being Seen",
    "Short Description of your work (1 sentence)": "Being Seen is a project that allows South Asian American Women the opportunity to create their own narratives by reflecting on their past experiences.",
    "Long Description of your work (4-6 sentences)": "South Asian American women (SAAW) are constantly rendered invisible in the United States. Frequently, they are pitted against themselves, each other, and society due to cultural norms and stereotypes. Now more than ever, it is crucial that South Asian American women feel like they have a safe place to go where they can discuss their experiences and educate themselves about their culture. Being Seen (@beingseen2021) is a project that lives on Instagram and gives SAAW the opportunity to self-reflect, heal, and learn through AR filters.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=14H6pkbbKe7kk2nza5VH2LFxZyPEfb-8Q",
    "Supporting Images": "",
    "Project Link": "https://beingseen2021.com/work",
    "Project Hashtag #": "#BeingSeenSAAW",
    "Project Themes & Keywords": "South Asian American Women, Augmented Reality, Social Media, Mental Health, Self-Healing, Culture, History"
  },
  {
    "Timestamp": "2021/11/28 1:55:42 AM EST",
    "Username": "ssl528@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Soham Lakade",
    "Email": "sohamlakade4@gmail.com",
    "Net ID": "ssl528",
    "Link to your personal portfolio": "https://www.behance.net/sohamlakade4",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1YubQ_ywddsObe_2eNchdj6oGTrNqDCvi",
    "Supplementary photos": "",
    "Instagram Handle": "soham_lakade",
    "Linked In": "www.linkedin.com/in/soham-lakade",
    "Twitter Handle": "sohamlakade04",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Final Year Grad (Thesis Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "UX design",
    "Title of your project": "Self-help application based on the philosophy of Bhagavad Gita",
    "Short Description of your work (1 sentence)": "An application which can help people live a vedantic, consciousness based philosophy in the western world",
    "Long Description of your work (4-6 sentences)": "Today, we all look at the world only through the western materialistic lens. Vedantic philosophy intrigued me, as it gives an alternate consciousness-based perspective to look at the world as well as ourselves. I was influenced by the Bhagavad Gita philosophy and soon realised how difficult it was to follow such a philosophy in today's world full of distractions. So I wanted to create a solution for beginners who wanted to follow this philosophy. This application helps users analyse their daily activities by thinking about the intention behind performing it. And accordingly, displays a mode mentioned in the philosophy which is dominant in the user and help the user to travel towards the correct mode.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1fK0r5fVE1UESfTu99IZbyibDlAfkeP6G",
    "Supporting Images": "",
    "Project Link": "https://www.figma.com/proto/le4BoXlr3ZfD8k4YJEoeSP/Untitled?page-id=0%3A1&node-id=56%3A526&viewport=241%2C48%2C0.29&scaling=scale-down&starting-point-node-id=56%3A526&show-proto-sidebar=1",
    "Project Hashtag #": "#selfhelp",
    "Project Themes & Keywords": "self-help, culture specific technology"
  },
  {
    "Timestamp": "2021/11/28 11:51:37 AM EST",
    "Username": "jk6185@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Jihyun (Jen) Kwon",
    "Email": "jk6185@nyu.edu",
    "Net ID": "jk6185",
    "Link to your personal portfolio": "jenjkwon.com",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1CbVSMiraCTY15fhWjNKJiyYmcBYoxZi2",
    "Supplementary photos": "",
    "Instagram Handle": "",
    "Linked In": "https://www.linkedin.com/in/jenjkwon/",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "https://vimeo.com/user129012481",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "3D Environment",
    "Title of your project": "Serene Space",
    "Short Description of your work (1 sentence)": "Serene Space is a 3D visualization of a connected quiet space.",
    "Long Description of your work (4-6 sentences)": "Inspired by visits to museums, Serene Space became the 3D visualization of my very own quiet place. The 3D environment aimed to capture a sense of tranquility through the colors, lighting, textures, and spatial design of the space. Each individual room reflects a different aesthetic but embraces the general modern feel. The space is made to be an escape from the everyday life full of worries and anxieties.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1_rDzkUu2W1D8AldcgrlRaDQOq5x9-UNY",
    "Supporting Images": "",
    "Project Link": "https://www.jenjkwon.com/work/serene-space",
    "Project Hashtag #": "#3D, #spatialdesign, #environmentart, #quietplace",
    "Project Themes & Keywords": "immersive environment, mental health"
  },
  {
    "Timestamp": "2021/11/28 3:10:16 PM EST",
    "Username": "vvs275@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Vido Shaweddy",
    "Email": "vvs275@nyu.edu",
    "Net ID": "vvs275",
    "Link to your personal portfolio": "https://vidoshaweddy.com",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1TCXadUYwea_VJULR4nC_Xb7uVYh0LIpP",
    "Supplementary photos": "",
    "Instagram Handle": "vidovalianto",
    "Linked In": "https://www.linkedin.com/in/vido-shaweddy-189294134/",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Final Year Grad (Thesis Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Mobile App/UX",
    "Title of your project": "PairUp",
    "Short Description of your work (1 sentence)": "A mobile app that quickly matches two book readers to swap their used books.",
    "Long Description of your work (4-6 sentences)": "PairUp is a mobile app that quickly matches two avid book readers to swap their print books. PairUp users populate their collection and wishlist, then it will intelligently find the book lovers they can trade titles with.\n\nThe project is inspired by book-swapping communities in social media that are having difficulty matching people. PairUp uses barter as the transaction system to help the environment and build trust among peers in a book community.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1oa9ZhYuaAAGGOtmtGlTwvFU2DdTtW4eS",
    "Supporting Images": "",
    "Project Link": "https://bit.ly/idmpairup",
    "Project Hashtag #": "#ios, #ux, #book, #mobile, #barter",
    "Project Themes & Keywords": "communication, barter, book, mobile apps"
  },
  {
    "Timestamp": "2021/11/28 4:23:17 PM EST",
    "Username": "kb2802@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Katelynn Browne",
    "Email": "kb2802@nyu.edu",
    "Net ID": "kb2802",
    "Link to your personal portfolio": "https://katelynnbrowne.com/",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1CfpEMH8VypCRGJKrjS2oshmaDj0pOguw",
    "Supplementary photos": "",
    "Instagram Handle": "",
    "Linked In": "https://www.linkedin.com/in/katelynnbrowne/",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Final Year Grad (Thesis Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Augmented Reality Zine",
    "Title of your project": "Cyber-Woman",
    "Short Description of your work (1 sentence)": "Cyber-Woman is an augmented reality zine that prompts women to question the alleged \"progressive\" nature of new technologies, by analyzing the impact of remote work technology on women during the pandemic.",
    "Long Description of your work (4-6 sentences)": "In American culture, we often view technology as either a neutral and logical force, or a force for progress and change. Throughout the COVID-19 pandemic, many office jobs were converted into full-time remote jobs for the past two years, thus further blurring the lines between digital and physical reality. Drawing on Marxist feminist theory, which argues that massive technological shifts have historically reversed women's progress, I created Cyber-Woman to explore the ways in which remote work technology has negatively impacted women. \n\nCyber-Woman is an augmented reality zine that uses essays in combination with collage, AR, and 3D scan art pieces in order to discuss the various ways in which remote work technology can act to oppress women. I used these mediums in order to convey that the blurring of physical and digital reality are working to harm women. The zine works by using QR codes that link to the AR experiences that are uploaded onto Instagram.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1ZDI42xycIdX9oj-Vph2jhMrV7CpFH7X9",
    "Supporting Images": "IMG_3839 - Katelynn Browne.jpg, IMG_3832 - Katelynn Browne.jpg",
    "Project Link": "https://katelynnbrowne.com/work/cyberwoman",
    "Project Hashtag #": "",
    "Project Themes & Keywords": "augmented reality, augmented reality activism, zine, design, feminism"
  },
  {
    "Timestamp": "2021/11/28 5:59:05 PM EST",
    "Username": "nl1652@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Nan Lin",
    "Email": "nl1652@nyu.edu",
    "Net ID": "nl1652",
    "Link to your personal portfolio": "https://wp.nyu.edu/nan_lin_portfolio/",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1dP_MLmlJFG5RstCeyuKmwTieXQ7z1d0k",
    "Supplementary photos": "",
    "Instagram Handle": "",
    "Linked In": "",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Website",
    "Title of your project": "Cycle",
    "Short Description of your work (1 sentence)": "A video about gender discrimination.",
    "Long Description of your work (4-6 sentences)": "As a girl who grow up in a conservative country, I want to use this project to show the gender discrimination a girl would face as she grow up. I want to focus the project about misogyny and feminism, I hope girls who grow up in a conservative country can resonance with this project. This project was inspired by the book \"Down Girl\" by Kate Manne, and it talked about the logic of misogyny. I just want to express my emotion through this piece, I hope it will help others to express their emotion as well.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1TK1rotEit1Zzq_WI5H4Ja49pT50Za5Qi",
    "Supporting Images": "",
    "Project Link": "https://wp.nyu.edu/nanlin_seniorproject/2021/11/28/project-link/",
    "Project Hashtag #": "#feminism # misogyny",
    "Project Themes & Keywords": ""
  },
  {
    "Timestamp": "2021/11/28 7:17:08 PM EST",
    "Username": "nv24@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Nart Varoqua",
    "Email": "nv24@nyu.edu",
    "Net ID": "nv24",
    "Link to your personal portfolio": "auqoravtran.com",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1g3Xjhf5193j66foUmhwN1HC7n5QOfAKK",
    "Supplementary photos": "",
    "Instagram Handle": "apologyturing",
    "Linked In": "https://www.linkedin.com/in/nart-varoqua-ab748374/",
    "Twitter Handle": "quavaro",
    "Youtube": "https://www.youtube.com/channel/UCoAEYcPiVW6dqPKDFFcsXgA",
    "Vimeo": "",
    "What year are you?": "Final Year Grad (Thesis Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Videos/Website",
    "Title of your project": "Apology Tour",
    "Short Description of your work (1 sentence)": "Using deepfake video as a critical design medium",
    "Long Description of your work (4-6 sentences)": "In recent years, deepfake videos—videos generated with machine learning—have garnered negative coverage in the media, primarily over concerns that the technology will be used to spread misinformation and fake news. This project is an attempt to examine that discourse more critically and use the technology in an artistic way. In the spirit of critical media interventions like those conducted by the Yes Men, I try to use deepfakes to render a speculative world in which those with power and influence apologize for the wrongs they have committed and thus far succeeded in living down. When people view these videos and realize they are fake, they will hopefully wonder, “Why isn’t this real?”",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1MelWc4X-zh8LrCA2bg6MPj70O_ANdni-",
    "Supporting Images": "",
    "Project Link": "auqoravtran.com/apologytour/",
    "Project Hashtag #": "",
    "Project Themes & Keywords": "emerging technology"
  },
  {
    "Timestamp": "2021/11/28 7:36:02 PM EST",
    "Username": "ch3110@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Christian Huh",
    "Email": "ch3110@nyu.edu",
    "Net ID": "ch3110",
    "Link to your personal portfolio": "https://christianhuh.github.io/Final/index.html",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1rdY2nbMkJ7clBhKv66XnrP8l6KxLaDkn",
    "Supplementary photos": "",
    "Instagram Handle": "c_w1sh",
    "Linked In": "https://www.linkedin.com/in/christianhuh/",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Video of finished product (3D model)",
    "Title of your project": "Valorant in Maya",
    "Short Description of your work (1 sentence)": "A 3D model representation of an in-game environment",
    "Long Description of your work (4-6 sentences)": "I mainly decided to work on this project because there weren't many things that I was interested in doing. I decided to incorporate a skill that I relatively had an easy time learning with a game that I enjoyed playing during my free time. I wanted to create a 3D model of an in-game environment to add to my portfolio. Working on this project was mainly for myself by trying to figure out if I was truly interested in this area of work.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1zNf_b7YMKM9KDX9jb_krMn7sBqhlgAfi",
    "Supporting Images": "",
    "Project Link": "https://wp.nyu.edu/christian_senior_project/",
    "Project Hashtag #": "",
    "Project Themes & Keywords": ""
  },
  {
    "Timestamp": "2021/11/28 7:39:56 PM EST",
    "Username": "xz2337@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Xinyue Zhang",
    "Email": "xz2337@nyu.edu",
    "Net ID": "N13930597",
    "Link to your personal portfolio": "xinyuezhang.myportfolio.com",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1Bmnj5NL_s0mqQ9FI4hee4gQixOaLaWvF",
    "Supplementary photos": "",
    "Instagram Handle": "@c42zzzz",
    "Linked In": "",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Installation",
    "Title of your project": "Blooming",
    "Short Description of your work (1 sentence)": "An interactive installation in a clear, plastic box.",
    "Long Description of your work (4-6 sentences)": "This project aim to provide audiences with an experience to give support to a non-living object and receive feedbacks. It is inspired from the idea of “pet rock” and discusses the potential emotional bonds between humans and inanimate objects. This project is a small clay sculpture in the form of an embryo placed inside of a 12 inches square box. An arduino board is used to create additional visual effects and interactive elements",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1nnnZa3pTurV8Mv50mmKYquI4_XFJcHjS",
    "Supporting Images": "",
    "Project Link": "https://wp.nyu.edu/tandonschoolofengineering-c42zzzz/",
    "Project Hashtag #": "",
    "Project Themes & Keywords": ""
  },
  {
    "Timestamp": "2021/11/28 9:02:48 PM EST",
    "Username": "gtl245@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Gina Liu",
    "Email": "gtl245@nyu.edu",
    "Net ID": "gtl245",
    "Link to your personal portfolio": "https://gldance.myportfolio.com/",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1Z49MdJJevGXf9T4EwexLFGvU6alMJufG",
    "Supplementary photos": "",
    "Instagram Handle": "umbrellafi5h",
    "Linked In": "https://www.linkedin.com/in/gina13liu/",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Installation/Website/Motion Graphics",
    "Title of your project": "New Sights",
    "Short Description of your work (1 sentence)": "A unique experience of traveling in Manhattan through different perspectives and forms.",
    "Long Description of your work (4-6 sentences)": "Inspired by the various cultures, histories, and environments that make up the neighborhoods in Manhattan, \"New Sights\" is an experimental experience created with motion graphics that give audiences the chance to explore Manhattan through different perspectives. You will navigate between five locations throughout the lower half of Manhattan and will “travel” to these locations through motion graphics. These motion graphics are inspired by the soundscapes and histories of the locations, and they each feature a different style and form of motion to showcase the neighborhood. After being stuck inside for more than a year due to COVID, I want to provide an immersive experience of various cultures and locations just with a simple click of a button.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1m7QCj2xa9CLrVBCAp7wvs7v1rWi_YPP-",
    "Supporting Images": "",
    "Project Link": "https://newsights.github.io/",
    "Project Hashtag #": "#Manhattan, #environment, #newperspectives, #motiongraphics, #design, #installation",
    "Project Themes & Keywords": ""
  },
  {
    "Timestamp": "2021/11/28 10:02:26 PM EST",
    "Username": "al5878@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Angie Li",
    "Email": "al5878@nyu.edu",
    "Net ID": "al5878",
    "Link to your personal portfolio": "https://angie-li.myportfolio.com/",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1ZTtPUtNkzP3YMrXqK4HfBi94Yorjr7HA",
    "Supplementary photos": "",
    "Instagram Handle": "imangie2",
    "Linked In": "https://www.linkedin.com/in/angie-li-a8434016b/",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Video",
    "Title of your project": "Locked Away",
    "Short Description of your work (1 sentence)": "A short (live action & animated) film that follows a girl with a treasure map, who discovers what is locked away.",
    "Long Description of your work (4-6 sentences)": "I hope that this short film can help the audience realize that no matter what different journeys that they are on, that the real \"magic\" is inside them. I’ve always found myself caught in wishing I could live in a fantasy world, whether in books, movies, or video games. In my past works I’ve explored the concept of magic vs. reality, childhood imagination, and the small moments that can seem magical. With this project, I want to dive deeper into the concept of magic with self exploration.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1Vnc3BwOve-SRIEUPTvkXKH_-6AvbJf9y",
    "Supporting Images": "",
    "Project Link": "https://vimeo.com/manage/videos/650957272",
    "Project Hashtag #": "",
    "Project Themes & Keywords": "Magic, Mystery, Self Revelation"
  },
  {
    "Timestamp": "2021/11/28 10:43:52 PM EST",
    "Username": "nj900@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Nelson James",
    "Email": "nj900@nyu.edu",
    "Net ID": "nj900",
    "Link to your personal portfolio": "nelsonajames.com",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1veXmrQ7W7eNPIVJZQjPSq917VT82UqU9",
    "Supplementary photos": "",
    "Instagram Handle": "nelsonajames",
    "Linked In": "https://www.linkedin.com/in/nelson-james-34a87a132/",
    "Twitter Handle": "N/A",
    "Youtube": "N/A",
    "Vimeo": "N/A",
    "What year are you?": "Final Year Grad (Thesis Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Toolkit",
    "Title of your project": "Gamify-It: A toolkit for teachers to gamify their existing lesson plans",
    "Short Description of your work (1 sentence)": "A toolkit to help teachers gamify their existing lesson plans.",
    "Long Description of your work (4-6 sentences)": "Gamify-It offers teachers the ability to transform their existing lesson plan content into an offline gamified lesson plan that they can share with students. The toolkit focuses on inclusivity by ensuring that differentiation techniques are built into the game to cater to a more diverse population of students. The aim of the toolkit is to assist teachers with using innovative pedagogical teaching methods to increase student retention and engagement in the classroom.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1joYjz7ViJ6XKk-GA_HfChbd2pR47PYL9",
    "Supporting Images": "",
    "Project Link": "https://www.nelsonajames.com/research/gamifyit",
    "Project Hashtag #": "#gamify-it",
    "Project Themes & Keywords": "gamification, communication, education, technology, curriculum, innovation, k12"
  },
  {
    "Timestamp": "2021/11/28 11:07:05 PM EST",
    "Username": "yh2797@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Yuzhi Huang",
    "Email": "yuzhih@nyu.edu",
    "Net ID": "yh2797",
    "Link to your personal portfolio": "https://yuzhihuang.cargo.site/",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1DdUXJgN2Nu8oZeo7HJDwJTwZ0mYU2fm-",
    "Supplementary photos": "",
    "Instagram Handle": "",
    "Linked In": "",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "https://vimeo.com/user133857736",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Video (Animation Short)",
    "Title of your project": "My Room",
    "Short Description of your work (1 sentence)": "A story about the bond between sisters, and a girl’s dream of her own room.",
    "Long Description of your work (4-6 sentences)": "My Room is a short animated film about the bittersweet experience of growing up sharing beds with siblings. The story is inspired by my own personal experience growing up with my sisters as well as a discussion thread post about being a girl who never had her own private bedroom, which was often a result of having near-age siblings and/or financial difficulty in the family. I want to share my own story to those who may have had similar experiences and can relate to the bittersweetness.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=18J9KuDWrvlOEcW4YeHCGQGp5mHlea5ae",
    "Supporting Images": "",
    "Project Link": "https://yuzhihuang.cargo.site/My-Room",
    "Project Hashtag #": "#Family #Growth #Self-Discovery",
    "Project Themes & Keywords": ""
  },
  {
    "Timestamp": "2021/11/28 11:12:59 PM EST",
    "Username": "lmm818@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Les Martinez",
    "Email": "lmm818@nyu.edu",
    "Net ID": "lmm818",
    "Link to your personal portfolio": "https://les88m.wixsite.com/lesmartinez",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1iYrTSi2-KFDPzeaHZOIhPVDfyE-rzvaL",
    "Supplementary photos": "",
    "Instagram Handle": "ahoysaber",
    "Linked In": "https://www.linkedin.com/in/les-martinez/",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Short film",
    "Title of your project": "Miasmic Incubus",
    "Short Description of your work (1 sentence)": "Miasmic Incubus is a two story short film about the kinds of nightmares we all experience.",
    "Long Description of your work (4-6 sentences)": "After two years of being back at home due to lockdowns, the move alone to NYC for my final semester was definitely difficult. I had several nightmares almost every night, and after speaking to friends and family about them, I had the idea to explore these nightmares in short films. With this project, I want to explore two concepts of nightmares: fleeing and freezing. Using Unreal Engine and motion capture, audiences will be able to view my experience of nightmares as best as I can recreate them. I hope to inspire audiences to view their nightmares as less scary and instead encourage them to talk about and explore their own nightmares.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1NJwmNawAMNm1bn8A4_ITMJQTVKJ2Pr9T",
    "Supporting Images": "",
    "Project Link": "https://les88m.wixsite.com/miasmicincubus",
    "Project Hashtag #": "#MiasmicIncubus",
    "Project Themes & Keywords": "3D cinema, psychology, dreams, unreal engine"
  },
  {
    "Timestamp": "2021/11/28 11:40:03 PM EST",
    "Username": "adm612@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Amanuel Mebrahtu",
    "Email": "adm612@nyu.edu",
    "Net ID": "adm612",
    "Link to your personal portfolio": "https://adm612.myportfolio.com/",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1WrLfdq1bpfDqkK4ncMq3Jo38SMznLS9o",
    "Supplementary photos": "",
    "Instagram Handle": "",
    "Linked In": "",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "UX Prototype",
    "Title of your project": "Writerly",
    "Short Description of your work (1 sentence)": "Writerly is a platform designed to help fiction writers better their work.",
    "Long Description of your work (4-6 sentences)": "Writerly is a Figma prototype of a potential web/local platform. I chose to make this project in particular because despite majoring in IDM I have always loved writing fiction. When writing, one of the major problems I tend to come across is the feeling that the work I produce lacks overall cohesion. This platform is designed for writers that tend to face a similar problem and would like a tool that helps them gauge whether or not their project is coming together in a way that make sense as a whole. In addition to helping with structure/cohesion, Writerly also features writing exercises and a community hub in which one may search for writers groups.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1ZX7s97mXHnFZb5-j_Lf92Dn1OKB7pkJ1",
    "Supporting Images": "",
    "Project Link": "https://www.figma.com/file/p8A4q3G21jToqtw22W8e6d/Untitled",
    "Project Hashtag #": "",
    "Project Themes & Keywords": ""
  },
  {
    "Timestamp": "2021/11/28 11:57:21 PM EST",
    "Username": "mct428@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Michelle Tabansi",
    "Email": "mct428@nyu.edu",
    "Net ID": "mct428",
    "Link to your personal portfolio": "https://michelletabansi.myportfolio.com/",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=13Pit6LRDfs3zwGJd9iOUFOJ-aesDj81O",
    "Supplementary photos": "",
    "Instagram Handle": "@themichelletabansi",
    "Linked In": "https://www.linkedin.com/in/michelle-tabansi-6b3344157/",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Video",
    "Title of your project": "how the tortoise overcame the elephant and the hippopotamus",
    "Short Description of your work (1 sentence)": "This is an animation depicting the west African folktale 'how the tortoise overcame the elephant and the hippopotamus'",
    "Long Description of your work (4-6 sentences)": "For my senior project I wanted to do something I was passionate about, so I decided to combine 2 things I love and feel very strongly about - my culture and animation/motion design. I'm from Nigeria and when I remember how when I was younger my grandfather would tell my siblings and I folktales, orally passed down stories that usually had a moral attached to them or were used to explain phenomena in nature. I always enjoyed these stories and wanted to represent them in a way that also paid homage to African art styles which are often abstract and elaborately patterned.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1pJ9g626ubxNbLRgHeo6AZKNlaJORBZ1E",
    "Supporting Images": "",
    "Project Link": "https://wp.nyu.edu/tandonschoolofengineering-michelletabansi/",
    "Project Hashtag #": "",
    "Project Themes & Keywords": ""
  },
  {
    "Timestamp": "2021/11/28 11:59:29 PM EST",
    "Username": "js9767@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Junwei Shi",
    "Email": "js9767@nyu.edu",
    "Net ID": "js9767",
    "Link to your personal portfolio": "https://js9767.myportfolio.com",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=18RBc8tOiUsj7xs8mEoK2QQY3-S_6RixM",
    "Supplementary photos": "",
    "Instagram Handle": "",
    "Linked In": "",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "UX",
    "Title of your project": "Time keeper",
    "Short Description of your work (1 sentence)": "This is a time management tool for young adults.",
    "Long Description of your work (4-6 sentences)": "As in nowadays society, we young adults want to have more than one skills in order to perform better in society. We want to be skillful in many different fields. However, it is hard to perfectly spread time to do everything we want and there are too many distractive things around us. So I design this tool for this group of people. It's easy to use and have nice interface that fits young people's taste.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1JaIDQJPx5RoE47gRnOdH7ww6sprdw1dD",
    "Supporting Images": "",
    "Project Link": "https://drive.google.com/drive/folders/1wLLprT7kZdMGL96NVET53eNVUXmcNnCu?usp=sharing",
    "Project Hashtag #": "",
    "Project Themes & Keywords": ""
  },
  {
    "Timestamp": "2021/11/29 12:21:43 AM EST",
    "Username": "jba9756@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Janelle Olive Algarra",
    "Email": "jba9756@nyu.edu",
    "Net ID": "jba9756",
    "Link to your personal portfolio": "n/a",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1PEXkRFyXaMCr01DNRJIn9YgKj4NeB7uY",
    "Supplementary photos": "",
    "Instagram Handle": "@janelleolive",
    "Linked In": "https://www.linkedin.com/in/janelle-olive-algarra-750948179/",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "UX project",
    "Title of your project": "Locality",
    "Short Description of your work (1 sentence)": "Locality is an app that features small, local businesses promoting conscious consumerism.",
    "Long Description of your work (4-6 sentences)": "Locality was inspired by the rise of small businesses during the pandemic. Based in the Philippines, the app was created to provide a platform to local businesses and encourage users to shop sustainably. A growing trend in 2021 is \"conscious consumerism\" where people tend to look for brands that conduct ethical practices in the production of materials as well as supports a cause. Therefore, the app serves as an e-commerce platform where small businesses can create a digital storefront and users are able to find brands that cater to the causes they are passionate about.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1ZFgQI9tZUhJ9oKxmjs3h94KCUO2Gqvbs",
    "Supporting Images": "",
    "Project Link": "https://jba9756.wixsite.com/locality",
    "Project Hashtag #": "#supportlocal #localbiz #sustainableshopping",
    "Project Themes & Keywords": "Sustainable shopping, Local businesses, Conscious consumerism"
  },
  {
    "Timestamp": "2021/11/29 1:51:00 AM EST",
    "Username": "dsc462@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Dana Sy-Ching",
    "Email": "dsc462@nyu.edu",
    "Net ID": "N11585783",
    "Link to your personal portfolio": "https://danasyching.com/",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=14REz9F-Fl_g1Oqce2uc_GVyXfnaAZUOv",
    "Supplementary photos": "https://drive.google.com/u/0/open?usp=forms_web&id=1vRAgZr9kNjSuXCik9unblhXRO__x_avA",
    "Instagram Handle": "",
    "Linked In": "www.linkedin.com/in/danasyching",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Physical Computing/Interactive Project",
    "Title of your project": "Echoes",
    "Short Description of your work (1 sentence)": "‘Echoes’ is an interactive project that is an exploration of movement and sound.",
    "Long Description of your work (4-6 sentences)": "‘Echoes’ explores movement and sound by reversing their roles while facilitating this reversal through forms of play and interaction. It is inspired by how dance, movement, and music positively affect people of all ages by bringing out creativity and by bringing us back into the physical world.\n\nThis project is for those who are seeking something new or for those who need to take a step back and remember the feeling of exploration. Apart from this, the project can facilitate mindful movement which could be beneficial in fields like physical therapy.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1EUF2n2Ff5eQqGJU0J-588HXFZKnYJuIq",
    "Supporting Images": "",
    "Project Link": "https://senior.danasyching.com/",
    "Project Hashtag #": "#movement #music #physicalcomputing #play #mindfulness",
    "Project Themes & Keywords": "physical computing, wireless communication, movement, creativity, exploration"
  },
  {
    "Timestamp": "2021/11/29 3:05:53 AM EST",
    "Username": "dy2040@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Danshan Yin",
    "Email": "dy2040@nyu.edu",
    "Net ID": "N13903030",
    "Link to your personal portfolio": "danshan.one/rideo",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1rCOX0oacfoQo8ZD40A87X_zNTDwQpRhK",
    "Supplementary photos": "",
    "Instagram Handle": "__wesley_",
    "Linked In": "www.linkedin.com/in/danshanyin",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Final Year Grad (Thesis Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "UX Design",
    "Title of your project": "RIDEO",
    "Short Description of your work (1 sentence)": "An interactive self-driving car experience design for riders",
    "Long Description of your work (4-6 sentences)": "With the new emergence of advanced technology, increasing numbers of vehicles begin to include self-driving features to enhance driving efficiency and some companies also start providing robotaxi services in certain places. I was inspired to create an in-car infotainment system that not only informs users about the driving behaviors of the vehicle but also elevates the riding experience during the trip. Through the interactions with the system, users can understand real-time information about the drive, acquire a sense of trust, and alleviate the feelings of confusion and anxiety to truly enjoy the riding experience.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1131fNa4e_euheBNYW7MzqGMS-Bxy8BcL",
    "Supporting Images": "",
    "Project Link": "danshan.one/rideo",
    "Project Hashtag #": "",
    "Project Themes & Keywords": "Self-driving Cars, Robotaxi Services, Riding Experiences"
  },
  {
    "Timestamp": "2021/11/29 11:17:09 AM EST",
    "Username": "nj2087@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Nausheen Javed",
    "Email": "nausheenleo@gmail.com",
    "Net ID": "N17845724",
    "Link to your personal portfolio": "https://readymag.com/nausheen/portfolio/",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1m62TOnNJgZrzJtqY6jK0EHUZSWLGQ1d1",
    "Supplementary photos": "https://drive.google.com/u/0/open?usp=forms_web&id=10tYKkButnZkZj5KCFAGOZcH3cv4fy2Wq",
    "Instagram Handle": "https://www.instagram.com/gojagaaji/",
    "Linked In": "https://www.linkedin.com/in/nausheenjaved/",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "https://vimeo.com/user21913710",
    "What year are you?": "Final Year Grad (Thesis Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Web application",
    "Title of your project": "Tell me a story",
    "Short Description of your work (1 sentence)": "A web platform for children to create stories through games",
    "Long Description of your work (4-6 sentences)": "A web application encourages children to become observant as they create and share stories using technological devices in a manner that is constructive, therapeutic, and challenging.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1JLT8zUaYMdR4Gh4fWJ-s9ahxk-qzGAmT",
    "Supporting Images": "https://drive.google.com/u/0/open?usp=forms_web&id=1FJljffNAHYVWYBCfefZUG4hJRVUeDJT-;https://drive.google.com/u/0/open?usp=forms_web&id=15B-gv_zv81zM6z2zbbqIU5mLeqGK_r_P;https://drive.google.com/u/0/open?usp=forms_web&id=1t8E0CsClr8REzFobcVE0TlqQpASw_S2n",
    "Project Link": "https://readymag.com/nausheen/portfolio/",
    "Project Hashtag #": "storytelling, games, play, art therapy",
    "Project Themes & Keywords": "storytelling, games, play, art therapy, technology, webplatform"
  },
  {
    "Timestamp": "2021/11/29 12:17:54 PM EST",
    "Username": "slf445@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Sophia Ferrera",
    "Email": "sophferrera@gmail.com",
    "Net ID": "slf445",
    "Link to your personal portfolio": "sophine.online",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1o_XVMY7bki6YT-90PSBG0FLvz6TMxxpA",
    "Supplementary photos": "",
    "Instagram Handle": "sophine.online",
    "Linked In": "linkedin.com/in/sophiaferrera",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Short film",
    "Title of your project": "Are We What We Eat?",
    "Short Description of your work (1 sentence)": "Are We What We Eat?\" is a short film about American media’s complex relationship with gender and sexuality as they are represented in film and television.",
    "Long Description of your work (4-6 sentences)": "Through interviews of Gen-Z LGBTQIA+ individuals, analysis of popular films and television shows with queer representation, and reflections on my own experience with representation, I hope to find a correlation between negative portrayals of queer character and the unmet or misguided expectations of viewers as they have or continue to come of age.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1keufgmKy9RkX1uWpOzU7tWIymYBeEaa7",
    "Supporting Images": "",
    "Project Link": "https://www.sophine.online/are-we-what-we-eat",
    "Project Hashtag #": "#documentary #shortfilm #LGBTQ #representation",
    "Project Themes & Keywords": "LGBT, representation, documentary"
  },
  {
    "Timestamp": "2021/11/29 2:06:18 PM EST",
    "Username": "jhg7046@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Jenny Goodwin",
    "Email": "jhg7046@nyu.edu",
    "Net ID": "N12666982",
    "Link to your personal portfolio": "https://www.hahajenny.com",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1St0DIgatyD3ttz7w1ZslCs91VvGXYKjU",
    "Supplementary photos": "",
    "Instagram Handle": "",
    "Linked In": "",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Final Year Grad (Thesis Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "UX Research",
    "Title of your project": "Transportation Decision Making of Parents and Caregivers of Children / Adults with Cognitive Disabilities and Neurodiversity",
    "Short Description of your work (1 sentence)": "This thesis will explore attitudes and experiences of parents and caregivers of individuals with neurodiversity and cognitive impairments (e.g. autism, ADHD, memory loss, etc.), specifically when deciding transportation methods (e.g. personal car, public transportation, ride-share services).",
    "Long Description of your work (4-6 sentences)": "When it comes to Transportation-as-a-Service (TaaS), there are specific features that are intended to support users with accessibility needs. Some of these include wheelchair accessible cars, audio cues, screen reader enabled apps, etc. While these cover areas in motor, hearing, and visual disabilities, there is still a lack of research and solutions for cognitive disability needs for transportation in general and TaaS.\nThis thesis will explore attitudes and experiences of parents and caregivers of individuals with neurodiversity and cognitive impairments (e.g. autism, ADHD, memory loss, etc.), specifically when deciding transportation methods (e.g. personal car, public transportation, ride-share services). This exploratory research is designed to provide information on the experiences of parents / caregivers caring for those with cognitive disabilities and neurodiversity. It is hoped that specific information from this thesis will assist in developing relevant functions for assistive technologies in the Transportation-As-A-Service (TaaS) sector.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=12VNIc0k99Ts8XNj_EbryAYfWmlhfi3sm",
    "Supporting Images": "https://drive.google.com/u/0/open?usp=forms_web&id=1SORdFouE5MGg2FvGTz10jLMDWewVsOoi;https://drive.google.com/u/0/open?usp=forms_web&id=1t71jwgYY1Awcq7uKR-ZL5VQCjtGkt9e_;https://drive.google.com/u/0/open?usp=forms_web&id=13GJTKPeV1hWz7fsesztbOBuBMm76Ljfv",
    "Project Link": "https://www.hahajenny.com/thesis",
    "Project Hashtag #": "",
    "Project Themes & Keywords": ""
  },
  {
    "Timestamp": "2021/11/29 2:46:13 PM EST",
    "Username": "ms10297@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Mohammad Shatil",
    "Email": "ms10297@nyu.edu",
    "Net ID": "ms10297",
    "Link to your personal portfolio": "https://moshatil.com",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1fvAscNiXNTVbphuhjYoc48yzR2Qe5cMc",
    "Supplementary photos": "",
    "Instagram Handle": "",
    "Linked In": "",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Composite Photography Installation",
    "Title of your project": "Visual Sleepwalk",
    "Short Description of your work (1 sentence)": "I take pictures and composite them in a way to fit my imagination.",
    "Long Description of your work (4-6 sentences)": "My main goal was to take pictures in different places in the city and eventually end up with composites from every image. Initially I scouted out really nice places in the city which I could just look at and just gaze at, and eventually deeply think and wonder about.Then I start to take some notes on how I feel or what I can imagine or think about in the scenes or areas I am in. I then try to find the perfect shot, whether it be freehand with my camera or set up carefully with a tripod. My final step is to create the perfect compositions based on my imagination and feelings through photoshop. My overall goal is to display these views of the city through the eyes of me and my vivid imagination, I want my work to portray a sleepwalking or ethereal type of feeling.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1EQAssF5WBvoYjCnHY5z9Bvmial9uwuIG",
    "Supporting Images": "",
    "Project Link": "https://ms102976ecf.myportfolio.com",
    "Project Hashtag #": "#visualsleepwalk",
    "Project Themes & Keywords": "Compositions, Photography, Ethereal, Aesthetic"
  },
  {
    "Timestamp": "2021/11/29 2:47:39 PM EST",
    "Username": "jd3860@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Joya Das",
    "Email": "jd3860@nyu.edu",
    "Net ID": "N12811000",
    "Link to your personal portfolio": "https://openprocessing.org/user/189104?view=sketches",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1qpZBYHHgmlPu13sC5-sl7he4fSsG_C4G",
    "Supplementary photos": "https://drive.google.com/u/0/open?usp=forms_web&id=1JyIyFJe8PHCbU8EKZ32fL46DL9_oQt_q",
    "Instagram Handle": "",
    "Linked In": "",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Music Video",
    "Title of your project": "Galactica",
    "Short Description of your work (1 sentence)": "a music video that is suppose to be out of this world",
    "Long Description of your work (4-6 sentences)": "I made this because I really loved the design and work of unreal engine. I like working around with avatars and making them alive in a hyperrealistic world. The whole point of the video is to bring some calmness and awesomeness. I want viewers to enjoy a masterpiece i made.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1e67D4bbaauuMorqfsiYHDDtYt8uE74Ra",
    "Supporting Images": "",
    "Project Link": "https://jd3860.wixsite.com/seniorproject",
    "Project Hashtag #": "",
    "Project Themes & Keywords": ""
  },
  {
    "Timestamp": "2021/11/29 3:40:28 PM EST",
    "Username": "mc7112@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Crystal Chen",
    "Email": "mc7112@nyu.edu",
    "Net ID": "mc7112",
    "Link to your personal portfolio": "https://mc7112.wixsite.com/minyichenportfolio",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1-1ERX0v0aMe3ldb9-Ztcgpi2Goq0TRrz",
    "Supplementary photos": "",
    "Instagram Handle": "crystamyal",
    "Linked In": "www.linkedin.com/in/minyi-crystal-chen-2722b3181",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "A video",
    "Title of your project": "Jumping!",
    "Short Description of your work (1 sentence)": "A short video of various animation styles showing the application of animation principles",
    "Long Description of your work (4-6 sentences)": "As a beneficiary of smart tutorials, I'm always looking for an opportunity to create one that can demonstrate some popular concepts such as Disney's 12 principles of animation. Although there's already a perfect video showing those principle for people who start to learn about animation, I would love to make one that indicate the application of those principles. In the video, audience will see three characters jumping over a gap in their own styles with brief summary of how the animation was made. The goal is to show how animation principles are applied in various ways.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1F-1TzAKxKZUFyAzJL97h30vOyFo-npsd",
    "Supporting Images": "",
    "Project Link": "https://docs.google.com/presentation/d/1XJ-bXJV7h9Bop_rfVkMBV8tBA8phSkaAW6tgq0cWEeI/edit?usp=sharing",
    "Project Hashtag #": "#animationPrinciple#Maya",
    "Project Themes & Keywords": "animation, tutorial, 12principles"
  },
  {
    "Timestamp": "2021/12/02 11:49:51 AM EST",
    "Username": "mk7266@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Myra Khan",
    "Email": "mk7266@nyu.edu",
    "Net ID": "N13830052",
    "Link to your personal portfolio": "https://uxfol.io/khan.myra312",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1x1CKRGjdEZeCL8sH6c5H_lDag56qmwaW",
    "Supplementary photos": "",
    "Instagram Handle": "@myra312",
    "Linked In": "https://www.linkedin.com/in/myrakhan312/",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Final Year Grad (Thesis Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Website",
    "Title of your project": "The 99",
    "Short Description of your work (1 sentence)": "A website for sustainable solutions using local materials.",
    "Long Description of your work (4-6 sentences)": "I designed a water filtration system for the Ndor Eco village in Ghana. I partnered with Yao Foli to achieve this since he was a village local and started this great initiative. I then created a website which housed all water filtration solutions to help Foli and his village have easy access to data uploaded by students at NYU and other universities.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=17TNhXxlPDE5yNtP1bNEUyimhpRXVUmR2",
    "Supporting Images": "https://drive.google.com/u/0/open?usp=forms_web&id=1jEgrAfY-KEBnziNXBLatch_smM_azriL;https://drive.google.com/u/0/open?usp=forms_web&id=1qjU59AeqZ8YNdwweSSXS6JllOR7Lxtkk;https://drive.google.com/u/0/open?usp=forms_web&id=1OSitCGSjWMBK88L2j1ZYRt7s-a2Qtd7R;https://drive.google.com/u/0/open?usp=forms_web&id=16z8fssqEseDlYXj39NZhP2QqLgw0M9vT;https://drive.google.com/u/0/open?usp=forms_web&id=1zYf_Fo7X_zb-88EQjUmPmSxFRTPl2TmI;https://drive.google.com/u/0/open?usp=forms_web&id=1UYKhtGznoLncA6XZNGGtUSFS12HOqw7U;https://drive.google.com/u/0/open?usp=forms_web&id=1kdmeFtT8n1VCbw64x1EFDWW2JEu-TkMx;https://drive.google.com/u/0/open?usp=forms_web&id=1uZLKyQCNkc-QcsGl7FZ6LgaAlbHkgIq0",
    "Project Link": "https://www.figma.com/proto/jUBylGJTO0JDgTtKnHitwb/The-99-Website-Design?node-id=8%3A321&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=8%3A321",
    "Project Hashtag #": "The99",
    "Project Themes & Keywords": "Sustainability"
  },
  {
    "Timestamp": "2021/12/03 2:46:48 PM EST",
    "Username": "jsf449@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "Jenni Funt",
    "Email": "jsf449@nyu.edu",
    "Net ID": "Jsf449",
    "Link to your personal portfolio": "jennifunt.myportfolio.com",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1dZI1MX_fhxIgBDsUQ6knkGEUDawuypSj",
    "Supplementary photos": "",
    "Instagram Handle": "Jennifuntt",
    "Linked In": "https://www.linkedin.com/in/jenni-f-111372b9/",
    "Twitter Handle": "",
    "Youtube": "",
    "Vimeo": "",
    "What year are you?": "Senior (Senior Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Magazine",
    "Title of your project": "Made Up Mag",
    "Short Description of your work (1 sentence)": "Magazine spreads with all content made by me.",
    "Long Description of your work (4-6 sentences)": "I made this magazine to showcase a wide range of my design skills. I utilized a multitude of Adobe programs to make each spread come to life. From product photography to product design to logo design to layouts. Each aspect was done with intention.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1hwmZf1h1tT8WNQ19ic5AzVizkFJp2fnk",
    "Supporting Images": "",
    "Project Link": "https://wp.nyu.edu/tandonschoolofengineering-jennifunt/",
    "Project Hashtag #": "",
    "Project Themes & Keywords": ""
  },
  {
    "Timestamp": "2021/12/04 12:17:33 AM EST",
    "Username": "ym1586@nyu.edu",
    "Are you an IDM Major, Minor, Abu Dhabi, or Shanghai student?": "Yes",
    "Full Name": "YUANCHEN MA",
    "Email": "YM1586@NYU.EDU",
    "Net ID": "YM1586",
    "Link to your personal portfolio": "https://drive.google.com/drive/folders/1-2vH-COasaj3Qp01eoZHvIn9piFgkZN-?usp=sharing",
    "Profile Picture": "https://drive.google.com/u/0/open?usp=forms_web&id=1i0CNF5n12Er7zLOptZ2_IJuFekl-q8a4",
    "Supplementary photos": "",
    "Instagram Handle": "chester_sj",
    "Linked In": "/",
    "Twitter Handle": "/",
    "Youtube": "/",
    "Vimeo": "/",
    "What year are you?": "Final Year Grad (Thesis Project)",
    "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "VR",
    "Title of your project": "Bond Street",
    "Short Description of your work (1 sentence)": "An immersive virtual reality experiences of bond street in Brooklyn.",
    "Long Description of your work (4-6 sentences)": "The project is an immersive virtual reality scene that allows users to enter and move freely through VR glasses. All modeling textures in the scene were taken manually.",
    "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1QLBaMSGHm4srpsZ7nyFru8MJw5trMB6k",
    "Supporting Images": "",
    "Project Link": "https://drive.google.com/drive/folders/1wPCBO3f9iBMFXr7-O7Vecbp3xlb0IKbs?usp=sharing",
    "Project Hashtag #": "",
    "Project Themes & Keywords": ""
  }
]
};
