let projectCollection = {
  "projects": [
    {
      "Full Name": "H. Jiang",
      "Net ID": "jia123",
      "Link to your personal portfolio": "https://engineering.nyu.edu/academics/programs/integrated-design-media-bs",
      "Instagram Handle": "idmnyu",
      "Linked In Handle": "shfitz",
      "Twitter Handle": "idmnyu",
      "Youtube": "UCZWnnNgDpXYT5MYGVKHqi0g",
      "What year are you?": "Second Year Grad (Thesis Project)",
      "Is this a group project?": "No",
      "If yes, list the first and last name of all group members (ex: Rose Nylund, Dorothy Zbornak, Blanche Devereaux)": "",
      "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Installation",
      "Title of your project": "The Placeholder Mask",
      "Short Description of your work (1 sentence)": "An exploration of anim tractavissent laborum tamen officia.",
      "Long Description of your work (4-6 sentences)": "My work explores the relationship between postmodern discourse and A sed magna vidisse ubi ingeniis e illum iudicem ubi ut magna commodo, eu minim non quem. Anim tractavissent laborum tamen officia. Eram mentitum eu multos multos in an culpa in quem. Est malis labore labore quamquam a ex illum aute ne ingeniis ita. Id legam duis magna proident ea ad a multos legam quis aut offendit tractavissent in commodo, probant e laborum, culpa eiusmod a graviterque in ea a sint velit anim.",
      "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1grOfek5cB48kyQ_9SZqfDLeEORoxKkNn",
      "Supporting Images": "",
      "Project Link": "https://en.wikipedia.org/wiki/Sophia_Petrillo",
      "Project Hashtag #": "#idmnyu",
      "Project Themes & Keywords": "emerging technology, communication, travel, film, video, masks, covid19"
    },
    {
      "Full Name": "Torem Kipsum",
      "Net ID": "kno123",
      "Link to your personal portfolio": "https://engineering.nyu.edu/academics/programs/integrated-design-media-bs",
      "Instagram Handle": "idmnyu",
      "Linked In Handle": "shfitz",
      "Twitter Handle": "idmnyu",
      "Youtube": "UCZWnnNgDpXYT5MYGVKHqi0g",
      "What year are you?": "Second Year Grad (Thesis Project)",
      "Is this a group project?": "No",
      "If yes, list the first and last name of all group members (ex: Rose Nylund, Dorothy Zbornak, Blanche Devereaux)": "",
      "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Installation",
      "Title of your project": "Haptic Breath",
      "Short Description of your work (1 sentence)": "A wearable art piece designed for connection and intimacy.",
      "Long Description of your work (4-6 sentences)": "This is a wearable art piece designed for connection and intimacy. It’s a pair of face masks with embedded electronics that allow you to stay connected with your friends and loved ones. Both face masks contain a breath sensor at the front and a vibrating motor that wraps around the back of each wearer’s neck. As one person breathes in and out, the haptic motor vibrates on the other person’s end, and vice versa. The wearable is meant to be integrated into each wearer’s day-to-day routine. The haptic messages are delivered via a BLE connection and provide a sense of presence for the other person on the other side. The breathing was chosen to make the experience of embodiment more intimate and less of a structured interaction. Using the form of a face mask, the project is in dialogue with our current state of social distancing practice due to COVID-19, not just as an artifact but also as a product of the pandemic.",
      "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1grOfek5cB48kyQ_9SZqfDLeEORoxKkNn",
      "Supporting Images": "img-1.jpg, img-2.jpg, model-a.1.JPG, model-a.2.JPG, model-a.3.JPG, model-b.1.JPG, model-b.2.JPG",
      "Project Link": "https://en.wikipedia.org/wiki/Sophia_Petrillo",
      "Project Hashtag #": "#idmnyu, #masklife",
      "Project Themes & Keywords": "product design, speculative design, masks, covid19, nature"
    },
    {
      "Full Name": "Lauren Ipsum",
      "Net ID": "gao123",
      "Link to your personal portfolio": "https://engineering.nyu.edu/academics/programs/integrated-design-media-bs",
      "Instagram Handle": "idmnyu",
      "Linked In Handle": "shfitz",
      "Twitter Handle": "idmnyu",
      "Youtube": "UCZWnnNgDpXYT5MYGVKHqi0g",
      "What year are you?": "Second Year Grad (Thesis Project)",
      "Is this a group project?": "No",
      "If yes, list the first and last name of all group members (ex: Rose Nylund, Dorothy Zbornak, Blanche Devereaux)": "",
      "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Installation",
      "Title of your project": "Plantree App",
      "Short Description of your work (1 sentence)": "An app that combines the reading management function and the visualization of personal reading achievement.",
      "Long Description of your work (4-6 sentences)": "Plantree is an app that combines the reading management function and the visualization of personal reading achievement. The users will be able to document what they read and what they plan to read in the app and their achievements on reading will be visualized by the trees. Each genre of books they read will be visualized as a tree in the user’s forest. The trees will change to a higher stage and change their appearance with the accumulation of books one has read. A clear vision of their knowledge will give users a clear view of what they have and where they can develop. Planting a tree in the app will enforce users’ sense of achievement and encourage them to actively enrich their knowledge. The app uses a style of pixel art which makes it more game-like compared to a traditional reading plan app. The interface is not all straight lines but includes curved graphics as status bar and the font is also pixel font which is coherent to the throughout style.",
      "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1grOfek5cB48kyQ_9SZqfDLeEORoxKkNn",
      "Supporting Images": "AE5EF71C-F188-4BD7-913B-27F9FC0E09EC.png",
      "Project Link": "https://en.wikipedia.org/wiki/Sophia_Petrillo",
      "Project Hashtag #": "#idmnyu",
      "Project Themes & Keywords": "emerging technology, communication, travel, nature"
    },
    {
      "Full Name": "Sophia Petrillo",
      "Net ID": "sp123",
      "Link to your personal portfolio": "https://engineering.nyu.edu/academics/programs/integrated-design-media-bs",
      "Instagram Handle": "idmnyu",
      "Linked In Handle": "shfitz",
      "Twitter Handle": "idmnyu",
      "Youtube": "UCZWnnNgDpXYT5MYGVKHqi0g",
      "What year are you?": "Second Year Grad (Thesis Project)",
      "Is this a group project?": "No",
      "If yes, list the first and last name of all group members (ex: Rose Nylund, Dorothy Zbornak, Blanche Devereaux)": "",
      "What are you submitting? (Website, Music, Game, Installation, UX, etc.)": "Installation",
      "Title of your project": "Flowers",
      "Short Description of your work (1 sentence)": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem.",
      "Long Description of your work (4-6 sentences)": "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.  Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.",
      "Main Image": "https://drive.google.com/u/0/open?usp=forms_web&id=1grOfek5cB48kyQ_9SZqfDLeEORoxKkNn",
      "Supporting Images": "img01 - Gabriella Cammarata.jpg",
      "Project Link": "https://en.wikipedia.org/wiki/Sophia_Petrillo",
      "Project Hashtag #": "#idmnyu",
      "Project Themes & Keywords": "emerging technology, communication, nature, travel"
    }
  ]
};
